#!/usr/bin/env python

# SCsub
Import('env')
Import("env_modules")

#TODO: https://docs.godotengine.org/en/3.1/development/cpp/custom_modules_in_cpp.html#improving-the-build-system-for-development

module_env = env_modules.Clone()
module_env.add_source_files(env.modules_sources, "*.cpp")
#module_env.Append(CXXFLAGS=[-std=c++17'])
